scaleapi/llm-engine

clients/python/llmengine/errors.py
docs/api/error_handling.md
mkdocs.yml

https://app.shortcut.com/scaleai/story/782395/documentation-for-possible-errors-in-the-client

Add documentation for error handling strategy and individual errors

---

clients/python/llmengine/fine_tuning.py

Will leave the changes to the training and validation docs to @seanshi-scale .

Add fine-tuning examples

---

clients/python/llmengine/data_types.py

Note that after @squeakymouse finishes renaming the server DTOs, we'll want to merge things (as in, docstrings from these client DTOs, etc.)

Add FineTune DTO docstrings

---

clients/python/llmengine/completion.py
clients/python/llmengine/data_types.py

@seanshi-scale @squeakymouse I think y'all will want to do something similar for fine tuning.
https://app.shortcut.com/scaleai/story/782480/documentation-for-completions-should-contain-more-details

Flesh out the docstrings for completion input params

---

docs/guides/rate_limits.md
mkdocs.yml

https://app.shortcut.com/scaleai/story/782495/guides-rate-limiting-guide

Rate limiting guide

---

docs/guides/fine_tuning.md

Flesh out Fine Tuning guide

---

clients/python/llmengine/fine_tuning.py
docs/guides/fine_tuning.md

Fine-tuning guides mention RLHF; add example in fine-tuning docs

---

clients/python/llmengine/client.py
clients/python/llmengine/data_types.py
server/llm_engine_server/common/dtos/llms.py

- remove traceback and status
- add request_id
- prompts -> prompt for sync

Some tweaks for LLM completions APIs

---

README.md

copied over content, also updated structure of Key Features / Features to Come

update README to reflect index.md content

---

README.md
clients/python/llmengine/completion.py

small fix for typo + broken link

fix typo and broken link

---

clients/python/llmengine/fine_tuning.py
docs/guides/fine_tuning.md

* Changed fine-tune defaults and removed `max_seq_length`

Changed fine-tune defaults and removed max_seq_length

---

docs/getting_started.md
docs/guides/completions.md
docs/index.md

Pages reviewed:
- Introduction
- Getting Started
- Model Zoo
- Guides/Completions
Checklist:

Fix up fine tooth comb issues. 

---

docs/guides/self_hosting.md
mkdocs.yml

Self-hosting guide docs. Helm chart params are being changed in this WIIP PR: https://github.com/scaleapi/llm-engine/pull/94. Wanted to get high-level comments earlier. 
Table based on existing helm chart standards: https://artifacthub.io/packages/helm/aws/aws-for-fluent-bit#configuration

[Experimental] Self-hosting Guide

---

docs/guides/fine_tuning.md

Add link to fine-tuning cookbook in fine-tuning guide page

---

server/llm_engine_server/infra/gateways/resources/k8s_endpoint_resource_delegate.py
server/tests/README.md

- Avoid calling `get_kubernetes_cluster_version()` in circleci
Pass CI `run_unit_tests_server`

Fix CI run_unit_tests_server 

---

docs/examples/finetuning.ipynb

This isn't llamav2 for cookbook, this is just various changes to make it a bit nicer

Updates to cookbook

---

clients/python/llmengine/__init__.py
clients/python/pyproject.toml
clients/python/setup.py

Bump pip package version from 0.0.0.beta3 -> 0.0.0.beta4. Package already published to pypi.

Bump pip package version from 0.0.0.beta3 -> 0.0.0.beta4

---

server/tests/README.md

Update the instruction for unit test. 
`PYTHONPATH=llm_engine_server WORKSPACE=. python3 -m pytest tests --cov=llm_engine_server` should be run from the `server/` folder

Update unit test instruction

---

examples/finetune_llama_2_on_science_qa.ipynb

ref https://github.com/scaleapi/llm-engine/issues/172

adding required dependency installs to scienceqa

---

.circleci/config.yml
docs/CNAME

Closes https://github.com/scaleapi/llm-engine/issues/189

Deploy docs from CI

---

clients/python/llmengine/__init__.py
clients/python/pyproject.toml
clients/python/setup.py

Bump and publish client version `beta8 -> beta9`

bump beta8 -> beta9

---

docs/guides/fine_tuning.md
docs/integrations.md
mkdocs.yml

Add integrations doc page

---

charts/model-engine/templates/_helpers.tpl
charts/model-engine/templates/service_template_config_map.yaml

This tag should be in requests in addition to limits

Add nvidia.com/gpu in requests

---

model-engine/model_engine_server/infra/services/image_cache_service.py
model-engine/tests/unit/infra/services/test_image_cache_service.py

Add new image to image cache

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/inference/vllm/Dockerfile
model-engine/model_engine_server/inference/vllm/vllm_server.py

- some fixes for vllm_server
- sync and stream completions
tested running some completions requests to a llama-2-7b endpoint

Completions for vLLM endpoints

---

model-engine/customer_service_data.csv
model-engine/model_engine_server/domain/use_cases/llm_fine_tuning_use_cases.py

Followup to @saiatmakuri's pr that added logic to check if `prompt, response` headers are valid. This is to check that the user passes in a valid file and surface an appropriate error message to them if they don't.

invalid CSV input returns InvalidRequestException

---

charts/model-engine/values_circleci.yaml
model-engine/model_engine_server/common/config.py
model-engine/model_engine_server/domain/entities/llm_entity.py
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/service_configs/service_config_circleci.yaml

As title. stop sequences is not yet supported.

Integrate LightLLM

---

clients/python/pyproject.toml
clients/python/setup.py

bump pypi version

---

model-engine/model_engine_server/infra/gateways/s3_llm_artifact_gateway.py

to fix bug with Model.create().

adding s3 session function instead of client function

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

Adding code llama to endpoints supported with TGI.
Code Llama is a Llama architecture, and thus supported for optimization with TGI.

Adding code llama to TGI

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/test_llm_use_cases.py

Return TGI errors

---

clients/python/README.md
clients/python/llmengine/api_engine.py

Provide proper auth for `post_file` route. Also fix documentation nit.

Patch `post_file` client method

---

charts/model-engine/templates/pod_disruption_budget.yaml
charts/model-engine/values_circleci.yaml
charts/model-engine/values_sample.yaml

- Add PDB to model-engine
- missing file

Add PodDisruptionBudget to model engine

---

model-engine/model_engine_server/core/celery/app.py
model-engine/model_engine_server/inference/forwarding/celery_forwarder.py
model-engine/model_engine_server/infra/gateways/celery_task_queue_gateway.py

Reverts scaleapi/llm-engine#345

Revert "Revert "fix celery worker profile for s3 access""

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

tested by creating a training deployment of the model and successfully sending completions requests through.

add new llm-jp models to llm-engine

---

charts/model-engine/values_sample.yaml

Fix sample.yaml

---

docs/model_zoo.md
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py

adds the zephyr 7b models (mistral 7b finetunes) for both alpha and beta versions of the models for completions. 

adding zephyr 7b

---

clients/python/llmengine/__init__.py
clients/python/pyproject.toml
clients/python/setup.py

bump the pypi version to `0.0.0beta20`.

pypi version bump

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

expands the zephyr model context window to 32k. 

overriding model length for zephyr 7b alpha

---

docs/model_zoo.md

Makes the documentation on model context window lengths clearer. This is useful to add because LLM Engine context windows are mostly but not always 1:1 with the model card context windows / purported max context windows, e.g. Mistral claims to be able to handle 32k context. 

update docs to show model len / context windows

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

Changing `code-llama` to `codellama` for naming conventions. 

change code-llama to codellama

---

charts/model-engine/Chart.yaml

Bump helm chart version

---

model-engine/model_engine_server/infra/services/live_model_endpoint_service.py
model-engine/tests/unit/infra/services/test_live_model_endpoint_service.py

Make sure metadata is not incorrectly wiped during endpoint update

---

charts/model-engine/values_sample.yaml

sensitive content flag

---

model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
model-engine/tests/unit/inference/test_vllm_batch.py

s5cmd has some quirkiness with aws profiles
tested with a job running codellama 34b

Fix permissions

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py

tsia
Spin up `codellama-70b` in internal cluster with 2 a100s

add codellama-70b models

---

model-engine/model_engine_server/api/model_endpoints_v1.py
model-engine/model_engine_server/common/constants.py
model-engine/model_engine_server/domain/exceptions.py
model-engine/model_engine_server/domain/use_cases/model_endpoint_use_cases.py
model-engine/tests/unit/domain/test_model_endpoint_use_cases.py

Add better validation for post inference hooks and support logging hook for python client.

Add hook validation and support logging for python client

---

model-engine/model_engine_server/inference/vllm/Dockerfile
model-engine/model_engine_server/inference/vllm/vllm_server.py

1. send a signal will print stack and pause the process. also include some utils
2. check start up time GPU usage
sent a `signal.SIGUSR1` signal and can see stacktrack, although doesn't seem like debug worked

add some debugging to vllm docker

---

model-engine/model_engine_server/infra/gateways/celery_task_queue_gateway.py

Add dd log statement when a celery task is added to the queue for async tasks.

Add log statement for gateway sending async task

---

model-engine/model_engine_server/infra/services/image_cache_service.py

cacher uses wrong repo name
tested by deploying

Fix cacher

---

model-engine/model_engine_server/infra/services/docker_image_batch_job_llm_fine_tuning_service.py

 fix llm-engine finetune.create failures

---

model-engine/model_engine_server/inference/batch_inference/vllm_batch.py

respect num new tokens
pending testing on real data

Tool completion respect num new tokens

---

model-engine/model_engine_server/inference/batch_inference/Dockerfile_vllm
model-engine/model_engine_server/inference/batch_inference/requirements.txt
model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
model-engine/model_engine_server/inference/infra/gateways/datadog_inference_monitoring_metrics_gateway.py
model-engine/tests/unit/infra/gateways/test_datadog_inference_monitoring_metrics_gateway.py
model-engine/tests/unit/infra/gateways/test_datadog_monitoring_metrics_gateway.py

add some metrics to batch jobs

Batch job metrics

---

docs/model_zoo.md
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py
model-engine/tests/unit/domain/test_llm_use_cases.py

attempted to create such an endpoint locally

Properly add mixtral 8x22b

---

model-engine/model_engine_server/inference/vllm/vllm_server.py

adds a potential catch block for asyncenginedead error handling.

adding asyncenginedead error catch

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/conftest.py
model-engine/tests/unit/domain/test_llm_use_cases.py

this is to preserve hand-tuned behavior for llama 3 70b

Hardcode llama 3 70b endpoint param

---

model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
model-engine/model_engine_server/inference/vllm/vllm_server.py

we don't always have permission to nvidia-smi (e.g. in MIG)

Don't fail checking GPU memory

---

docs/guides/completions.md

Malformed formatting on Completions guide - https://llm-engine.scale.com/guides/completions/

Fix formatting on completions documentation guide

---

charts/model-engine/templates/gateway_deployment.yaml

avoid preemption as much as possible

Higher priority for gateway

---

model-engine/model_engine_server/api/llms_v1.py

DEBUG: Add debug log for authz errors part 2

---

integration_tests/rest_api_utils.py
integration_tests/test_completions.py

Wait for gateway to be up on test start

---

model-engine/model_engine_server/inference/vllm/Dockerfile
model-engine/model_engine_server/inference/vllm/requirements-build.txt
model-engine/model_engine_server/inference/vllm/requirements.txt
model-engine/model_engine_server/inference/vllm/vllm_server.py

Bump vLLM to enable fp8 quantization on h100s
* Passed integration test ran locally
* Tested 
* precompiled mixtral-8x22b-instruct: https://huggingface.co/neuralmagic/Mixtral-8x22B-Instruct-v0.1-FP8 loads on 4H100
* precompile llama-3-70b-instruct: https://huggingface.co/neuralmagic/Meta-Llama-3-70B-Instruct-FP8 loads on 1H100 @ 95% gpu utilization

Bump vllm to v0.5.0.post1

---

.circleci/config.yml
.circleci/resources/.minikube-config-map
.circleci/resources/.minikube-registry-creds

we use IAM role instead of IAM user now

Fix AWS IAM role access

---

model-engine/model_engine_server/inference/vllm/requirements.txt
model-engine/model_engine_server/inference/vllm/vllm_server.py

Update vllm server to be OpenAI compatible
A lot of this was nabbed from https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py

Update vllm server to be openai compatible

---

clients/python/llmengine/errors.py

Fix some odd things I noticed in the client
Ran the changed fn locally

fix some oddities in the client

---

docs/model_zoo.md
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py
model-engine/tests/unit/domain/test_llm_use_cases.py

Add support for phi 3 models

---

model-engine/model_engine_server/api/app.py

add a first log in fastapi for debug purpose

Add earliest log

---

model-engine/model_engine_server/api/app.py

Log info instead of debug

---

model-engine/model_engine_server/inference/batch_inference/requirements.txt

We want to unblock DeepSeek V2 batch inference, which has been added to 0.5.1

Bump vllm batch version

---

charts/model-engine/values_circleci.yaml
charts/model-engine/values_sample.yaml
docs/model_zoo.md
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/test_llm_use_cases.py

Add deepseek models

---

charts/model-engine/values_circleci.yaml
charts/model-engine/values_sample.yaml
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/test_llm_use_cases.py

Reduce hardware requirement for deepseek coder lite

---

model-engine/model_engine_server/inference/batch_inference/requirements.txt
model-engine/model_engine_server/inference/vllm/requirements.txt

Bump vllm version to 0.5.3post1

---

model-engine/model_engine_server/db/base.py

Reduce connection pool size

---

charts/model-engine/templates/_helpers.tpl

add a label to distinguish between clusters

Add env label

---

clients/python/llmengine/__init__.py
clients/python/llmengine/api_engine.py
clients/python/llmengine/completion.py
clients/python/llmengine/model.py
clients/python/pyproject.toml
clients/python/setup.py

This enables custom auth header implementations

Enable passing in headers through the client

---

clients/python/llmengine/api_engine.py

Re-add auth header

---

model-engine/model_engine_server/common/service_requests.py
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/tests/unit/inference/test_http_forwarder.py

Remove the requirement to add models to model zoo in order to run batch inference via vllm as long as a checkpoint is provided

Allow support for vllm batch with checkpoints

---

model-engine/model_engine_server/inference/post_inference_hooks.py

Certain records aren't delivered to Snowflake but are successfully delivered to the firehose stream. After talking to AWS support, a suspicion is the record itself isn't a valid JSON object or contains double quotes/escape characters. Adding these log statements will help us test this hypothesis to add further validation if needed.

MLI-2510 Validate json logs to test hypothesis on no records in Snowflake

---

model-engine/model_engine_server/common/dtos/llms/batch_completion.py
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/inference/batch_inference/dto.py
model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
model-engine/tests/unit/domain/test_llm_use_cases.py

Not all use cases require full context model to be deployed; this change allows users to specify max context length to use for a batch job

Allow setting max context length for batch jobs

---

model-engine/model_engine_server/inference/batch_inference/dto.py

Fix dto for batch completion

---

clients/python/llmengine/__init__.py
clients/python/llmengine/data_types.py
clients/python/pyproject.toml
clients/python/setup.py

Update client with new max_context_length

---

model-engine/model_engine_server/api/v2/batch_completion.py
model-engine/model_engine_server/api/v2/common.py

Some cleanups for batch v2

---

clients/python/llmengine/completion.py
clients/python/llmengine/data_types/batch_completion.py
model-engine/model_engine_server/api/v2/batch_completion.py
model-engine/model_engine_server/common/dtos/llms/batch_completion.py

More batch job cleanup

---

model-engine/model_engine_server/inference/vllm/vllm_batch.py

Silly bug with list initialization. Caused tokens to be aggregated across all prompts XP

vllm_batch: Fix list initialization

---

.ruff.toml
model-engine/model_engine_server/db/migrations/alembic.ini
model-engine/model_engine_server/db/migrations/alembic/README
model-engine/model_engine_server/db/migrations/alembic/env.py
model-engine/model_engine_server/db/migrations/alembic/script.py.mako
model-engine/model_engine_server/db/migrations/alembic/versions/2024_09_09_1736-fa3267c80731_initial.py
model-engine/model_engine_server/db/migrations/initial.sql

Introduce alembic for proper db migration practices

Introduce alembic to repo

---

clients/python/llmengine/__init__.py
clients/python/llmengine/data_types/chat_completion.py
clients/python/pyproject.toml
clients/python/setup.py

Forgot to subclass pydantic basemodel
Right now vllm args passed through the cli are getting dropped before being sent to the server.

Fix passing in vllm args options

---

model-engine/model_engine_server/inference/vllm/vllm_batch.py

add skipping code to v2 batch

---

model-engine/model_engine_server/common/dtos/llms/model_endpoints.py
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

This allows users to redeploy endpoints to pick up changes in llm engine implementation in bundle creation even when the underlying endpoint spec hasn't changed

Enable users to force redeploy endpoints

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

Remove print statement

---

model-engine/model_engine_server/inference/vllm/vllm_batch.py

vllm oai completion requires raw request, which we don't have for batch completion. hack it by instantiating a dummy request.

Fix batch compeltion v2 for oai completion

---

model-engine/model_engine_server/infra/repositories/redis_model_endpoint_cache_repository.py

See title
TODO: Create a test deployment, see if it reads/writes to the right location in redis

Make Redis endpoint cache read service identifier

---

charts/model-engine/templates/service_template_config_map.yaml

set default storage request/limit for batch jobs

---

clients/python/llmengine/__init__.py
clients/python/llmengine/data_types/rest.py
clients/python/pyproject.toml
clients/python/setup.py

Add chat template override to client

---

model-engine/model_engine_server/common/dtos/llms/batch_completion.py
model-engine/model_engine_server/common/dtos/llms/vllm.py
model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/infra/services/fake_llm_batch_completions_service.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/conftest.py
model-engine/tests/unit/domain/test_llm_use_cases.py

* Add `trust_remote_code` support to unblock hosting specific models not supported directly by transformers (e.g. deepseek)
* Refactor vllm engine args pass through mechanism
* Enable specifying hardware spec for batch jobs

Enable more vllm args to be passed through for batch completions

---

charts/model-engine/templates/recommended_hardware_config_map.yaml

add rec hardware to the configmap yaml

---

model-engine/model_engine_server/inference/vllm/vllm_batch.py

try fixing bug in batch completions

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

Add this flag so we can provide proper model names through oai requests instead of having to overwrite the model field with `model_weights` 

Add served_model_name

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

Add 1b 3b to model zoo

---

model-engine/model_engine_server/inference/vllm/vllm_server.py

0.6.3 had some api change needed to fix for v1 completions codepath

Fix guided decoding logit setup

---

charts/model-engine/values_circleci.yaml
charts/model-engine/values_sample.yaml
model-engine/model_engine_server/infra/gateways/resources/image_cache_gateway.py
model-engine/model_engine_server/infra/gateways/resources/k8s_endpoint_resource_delegate.py
model-engine/model_engine_server/infra/gateways/resources/templates/service_template_config_map_circleci.yaml
model-engine/model_engine_server/infra/services/image_cache_service.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/infra/gateways/resources/test_image_cache_gateway.py
model-engine/tests/unit/infra/gateways/resources/test_k8s_endpoint_resource_delegate.py
model-engine/tests/unit/infra/services/test_image_cache_service.py

Add the H100 + mig splits to the image cache
Deploy to a test cluster, see that the daemonsets come up

Fix up the image caching functionality so it works with h100s

---

charts/model-engine/values_circleci.yaml
model-engine/model_engine_server/common/resource_limits.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/test_model_endpoint_use_cases.py

We actually have more space for storage on H100 nodes.
Unit test

increase storage limit for h100s

---

model-engine/model_engine_server/db/migrations/stamp_initial_schema.sh

Needed for graceful helm upgrade for environments that were deployed before we introduced alembic

Add script to stamp initial schema

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py

Safe handle model param

---

model-engine/model_engine_server/common/dtos/llms/vllm.py

Need these for launching mistral models

More vllm args passthrough

---

charts/model-engine/Chart.yaml
charts/model-engine/templates/balloon_deployments.yaml
charts/model-engine/templates/model_engine_default_priority_class.yaml
charts/model-engine/values.yaml
charts/model-engine/values_sample.yaml

Add larger balloons, allow default priority to prevent balloons optionally.
Check diff of helm upgrade

Changes to balloons to support a less "on-demand" style of compute

---

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
model-engine/model_engine_server/inference/vllm/build_and_upload_image.sh
model-engine/tests/unit/domain/test_llm_use_cases.py

Support vllm 0.6.4.post1
Add *.model.v* in s5cmd include flag. Needed for [pixtral large](https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411/tree/main)

Support pixtral large

---

model-engine/model_engine_server/api/model_endpoints_v1.py
model-engine/model_engine_server/common/dtos/model_endpoints.py
model-engine/model_engine_server/domain/services/model_endpoint_service.py
model-engine/model_engine_server/domain/use_cases/model_endpoint_use_cases.py
model-engine/model_engine_server/infra/gateways/live_model_endpoint_infra_gateway.py
model-engine/model_engine_server/infra/gateways/model_endpoint_infra_gateway.py
model-engine/model_engine_server/infra/gateways/resources/endpoint_resource_gateway.py
model-engine/model_engine_server/infra/gateways/resources/k8s_endpoint_resource_delegate.py
model-engine/model_engine_server/infra/gateways/resources/live_endpoint_resource_gateway.py
model-engine/model_engine_server/infra/services/live_model_endpoint_service.py
model-engine/tests/unit/api/test_model_endpoints.py
model-engine/tests/unit/conftest.py
model-engine/tests/unit/domain/test_model_endpoint_use_cases.py
model-engine/tests/unit/infra/gateways/resources/test_k8s_endpoint_resource_delegate.py
model-engine/tests/unit/infra/gateways/test_live_model_endpoint_infra_gateway.py
model-engine/tests/unit/infra/services/test_live_model_endpoint_service.py

as title. will return error for endpoints with more than 1 node
unit test and tested with prod deployments

API to restart deployment

---

clients/python/llmengine/__init__.py
clients/python/llmengine/completion.py
clients/python/llmengine/data_types/vllm.py
clients/python/llmengine/model.py
clients/python/pyproject.toml
clients/python/setup.py
model-engine/model_engine_server/common/dtos/llms/vllm.py

add arbitrary kwarg passthrough to model creation

---

scripts/throughput_benchmarks.py

Add SGLang as a target for the benchmarks script
Ran the script against SGLang run locally

Benchmark SGLang

---

charts/model-engine/templates/service_template_config_map.yaml

http forwarder not forwarding chat completion apis to leaderworkerset container

Fix chat completion support for multinode

---

charts/model-engine/templates/celery_autoscaler_stateful_set.yaml

Update stateful set rollout strategy

---

model-engine/model_engine_server/common/dtos/llms/vllm.py

Some args have default accidentally

Remove default args for chat completion

---

model-engine/model_engine_server/inference/vllm/vllm_batch.py
requirements-docs.txt

Limit concurrency of sendings requests to the vLLM engine when requests have guided decoding since there is a per request initialization cost that results in request loading taking longer than the default `VLLM_ENGINE_ITERATION_TIMEOUT_S` of 30s.

Handle large batches w/ guided decoding

---

model-engine/model_engine_server/inference/vllm/vllm_batch.py

Guided decoding detection needs to provide a reasonable default token > 0 in the case that the request itself doesn't provide it

fix edge case where max_tokens is not provided in requests

---

model-engine/model_engine_server/api/v2/common.py

this is making GET /batch error

Fix metric metadata handling

---

model-engine/model_engine_server/inference/sglang/sglang-startup-script.py

Update sglang startup script

---

charts/model-engine/values.yaml

Set runDbMigrationScript to true in values.yaml
