clients/python/llmengine/completion.py, docs/api/python_client.md
Note: I manually scrubbed `status` and `traceback` from the JSON, as we're going to be removing those in another ticket anyway.
New, for `Completion.create`:
New, for `Completion.acreate`:
=> Tweak examples for completions; remove doc section for Model

docs/guides/completions.md
https://app.shortcut.com/scaleai/story/782493/guide-update-completions-guide
Roughly tried to follow https://platform.openai.com/docs/guides/gpt/completions-api
=> Add more content to the Completions guide

docs/api/data_types.md, docs/api/python_client.md, mkdocs.yml
=> Refactor docs navigation to split out API and Data Type references

docs/guides/fine_tuning.md
Address:
The output should contain a fine_tuned_model like OpenAI. We should also update the docs to reflect that this fine_tuned_model is what gets sent to Completions.
We should also document how the suffixing works: f"{model}:{suffix}:{time_now}" if suffix is not None else f"{model}.{time_now}"
[[sc-782703]](https://app.shortcut.com/scaleai/story/782703/llm-service-finetuning-api-returns-model-name-to-user-and-job-ids-are-prefixed-with-ft-instead-of-job)
[[sc-782502]](https://app.shortcut.com/scaleai/story/782502/fine-tuning-job-response-should-contain-the-fine-tuned-model)
=> Update finetuning docs

docs/guides/self_hosting.md
Add a `Play With It` section in `docs/guides/self_hosting.md` to document… to how test sending a request and getting response via pod port forwarding.
The name `Play With It` comes from https://github.com/temporalio/helm-charts#play-with-it
=> Play With It section in self hosting doc

charts/llm-engine/templates/_helpers.tpl, charts/llm-engine/templates/service_template_config_map.yaml, charts/llm-engine/values_sample.yaml, docs/examples/finetuning.ipynb, server/llm_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, server/llm_engine_server/infra/gateways/resources/templates/service_template_config_map_circleci.yaml
- Add missing `a100` and `t4` devices in values_sample.yaml that prevent `llm-engine-cacher` from starting successfully.
- Update `http-forwarder` container python command path for streaming endpoint
- Fix TGI repo name and forwarder config path
- Fix forwarder aws config mount path
```
data = {
"name": "llama-7b",
"model_name": "llama-7b",
"source": "hugging_face",
"inference_framework": "text_generation_inference",
"inference_framework_image_tag": "0.9.1",
"num_shards": 4,
"endpoint_type": "streaming",
"cpus": 32,
"gpus": 4,
"memory": "40Gi",
"storage": "40Gi",
"gpu_type": "nvidia-ampere-a10",
"min_workers": 1,
"max_workers": 12,
"per_worker": 1,
"labels": {"team": "infra", "product": "llm_model_zoo"},
"metadata": {}
}
headers = {'Content-Type': 'application/json'}
response = …
```
=> Can create LLM endpoint

clients/python/llmengine/api_engine.py
Fetching the API key from the environmental variables at the top level of the file requires setting the environmental variable before importing the package, which may be a little awkward in notebooks. It also makes it hard to switch API keys.
=> Refetch API key dynamically

.circleci/config.yml
Helm Install was previously failing in CI. Use CI values and set image tag.
=> Patch Integration Test in CI

clients/python/llmengine/api_engine.py, clients/python/llmengine/data_types.py, clients/python/llmengine/model.py
```
LLM_ENGINE_BASE_PATH=xxx SCALE_API_KEY=yyy python
from llmengine import Model
Model.create(name="llama-7b-test", model="llama-7b", inference_framework_image_tag="0.9.3", checkpoint_path="s3://xxx/yyy.tar",public_inference=False)
```
=> Support checkpoint_path for endpoint creation

server/llm_engine_server/core/aws/roles.py
=> Fix typo in roles.py

clients/python/llmengine/data_types.py, clients/python/llmengine/fine_tuning.py, docs/model_zoo.md
- Integrate finetune with wandb
=> Integrate finetune with wandb

charts/llm-engine/values_sample.yaml, docs/guides/self_hosting.md
Add documentation on pointing `llmengine` client to self-hosted infrastructure.
=> Add documentation on pointing llmengine client to self-hosted infrastructure

clients/python/llmengine/data_types.py, clients/python/llmengine/model.py, docs/api/data_types.md, docs/guides/endpoint_creation.md
Per request to add status of model endpoint to `Model.get()`.
=> adding status field to model get response

server/llm_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
- don't depend on private docker image
- download from tar file or folder
- optimize s5cmd parameters
=> Faster s5cmd download

charts/llm-engine/templates/_helpers.tpl, charts/llm-engine/templates/service_template_config_map.yaml
=> Update service template

clients/python/llmengine/__init__.py, clients/python/llmengine/api_engine.py, clients/python/pyproject.toml, clients/python/setup.py
`os.path.join` is system-dependent, so it adds backslashes on Windows; this creates invalid routes. 
instead use `urllib.parse.urljoin` that is system independent and is built for joining URLs.
https://github.com/scaleapi/llm-engine/issues/170
https://github.com/scaleapi/llm-engine/issues/209
=> Fix API calls on Windows

model-engine/model_engine_server/api/dependencies.py, model-engine/model_engine_server/api/tasks_v1.py, model-engine/model_engine_server/common/config.py, model-engine/model_engine_server/common/dtos/tasks.py, model-engine/model_engine_server/domain/exceptions.py, model-engine/model_engine_server/domain/gateways/__init__.py, model-engine/model_engine_server/domain/gateways/inference_autoscaling_metrics_gateway.py, model-engine/model_engine_server/domain/gateways/streaming_model_endpoint_inference_gateway.py, model-engine/model_engine_server/domain/gateways/sync_model_endpoint_inference_gateway.py, model-engine/model_engine_server/domain/services/model_endpoint_service.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/domain/use_cases/streaming_inference_use_cases.py, model-engine/model_engine_server/domain/use_cases/sync_inference_use_cases.py, model-engine/model_engine_server/entrypoints/start_batch_job_orchestration.py, model-engine/model_engine_server/infra/gateways/__init__.py, model-engine/model_engine_server/infra/gateways/live_streaming_model_endpoint_inference_gateway.py, model-engine/model_engine_server/infra/gateways/live_sync_model_endpoint_inference_gateway.py, model-engine/model_engine_server/infra/gateways/redis_inference_autoscaling_metrics_gateway.py, model-engine/model_engine_server/infra/services/live_model_endpoint_service.py, model-engine/tests/unit/conftest.py, model-engine/tests/unit/infra/gateways/test_live_streaming_model_endpoint_inference_gateway.py, model-engine/tests/unit/infra/gateways/test_live_sync_model_endpoint_inference_gateway.py, model-engine/tests/unit/infra/services/conftest.py
Emit autoscaling metrics from gateway
Have sync endpoints poll + wait if it gets upstream not found
Next pr: make endpoints created with the keda object if we're scaling from zero
Also change how we're doing retries for sync endpoints in general, and add some optional fields to have some user control over retry behavior.
Note: this scales pods from 0 to 1, not 1 to N. Autoscaling works by looking at the length of a redis list, and the implementation intentionally keeps the list at length 1. We also set a timeout for the redis list at 1 minute.
=> Sync scale from zero, part 1

clients/python/llmengine/fine_tuning.py, docs/guides/fine_tuning.md
fine-tune guide specifies example of using llm engine's file upload
=> add file upload guidance to fine-tune docs

clients/python/llmengine/fine_tuning.py, docs/guides/fine_tuning.md
explicitly note that PeftConfig params are supported to be passed in as hyperparameters
=> add peft config documentation

charts/model-engine/templates/balloon_cpu_deployment.yaml, clients/python/llmengine/model.py, model-engine/model_engine_server/infra/services/image_cache_service.py
1. don't by default use 4 GPUs when creating models
2. Fix balloon CPU deployment
3. Fix cacher datetime comparison
tested cache by running locally against prod passing comparison code
=> Some fixes

model-engine/model_engine_server/api/worker.py
Gunicorn returns 503 instead of 429 when concurrency exceeds the limit, before adding rate limiting just increase the concurrency and see if that's good enough
=> Higher concurrency limit for gunicorn

model-engine/model_engine_server/api/worker.py
comment from https://github.com/scaleapi/llm-engine/pull/249
=> Add comments

clients/python/llmengine/data_types.py
previously, due to this not being implemented on the client side we had a bug where `vllm` based endpoints would raise errors during `Model.get()` and `Model.list()`, eg: 
after this change we have: 
```
GetLLMEndpointResponse(..., status=<ModelEndpointStatus.READY: 'READY'>, inference_framework=<LLMInferenceFramework.VLLM: 'vllm'>...
```
=> add vllm to inference framework enum

clients/python/llmengine/__init__.py, clients/python/pyproject.toml, clients/python/setup.py
increase the version to be 0.0.0b16. I already increased it to 0.0.0b15 but there was a bug that caused issues with the version check update message, I wanted to address it prior to announcing the version bump.
=> bump the llm engine pypi version

.pre-commit-config.yaml, clients/python/llmengine/data_types.py, docs/getting_started.md, docs/guides/completions.md, model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/api/test_llms.py, model-engine/tests/unit/api/test_tasks.py
- Fix streaming endpoint failure handling
before the fix, getting error:
```
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
after the fix, getting response:
```
b"data: {'error': {'status_code': 404, 'detail': 'Model endpoint a not found.'}}\r\n\r\n"
```
=> Fix streaming endpoint failure handling

.pre-commit-config.yaml, clients/python/llmengine/model.py, model-engine/model_engine_server/common/env_vars.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/domain/conftest.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Validate quantization values when creating endpoints
=> Validate quantization

model-engine/model_engine_server/infra/gateways/live_cron_job_gateway.py, model-engine/model_engine_server/infra/gateways/live_docker_image_batch_job_gateway.py, model-engine/tests/unit/infra/gateways/k8s_fake_objects.py, model-engine/tests/unit/infra/gateways/resources/test_k8s_endpoint_resource_delegate.py, model-engine/tests/unit/infra/gateways/test_live_docker_image_batch_job_gateway.py
Before, jobs would immediately start as RUNNING even if no pods were allocated, or if pods were PENDING.
testing:
started gateway on devbox, made requests to get/list docker image batch jobs on our clusters, saw that a RUNNING job had changed to PENDING correctly.
also unit tests
=> Properly return PENDING status for docker image batch jobs/fine tune jobs

model-engine/model_engine_server/api/app.py, model-engine/model_engine_server/api/dependencies.py, model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/core/loggers.py
Add `user_id` and `team_id` as additional log facets. Clean up the log tagging to be a bit more general. 
Tested `CustomJSONFormatter` locally and saw that request_id, user_id, and team_id are in the logger extras.
=> add user_id and team_id as log facets

charts/model-engine/templates/service_template_config_map.yaml, model-engine/model_engine_server/infra/gateways/resources/image_cache_gateway.py, model-engine/model_engine_server/infra/gateways/resources/k8s_endpoint_resource_delegate.py, model-engine/model_engine_server/infra/gateways/resources/k8s_resource_types.py, model-engine/model_engine_server/infra/gateways/resources/templates/service_template_config_map_circleci.yaml, model-engine/tests/unit/infra/gateways/resources/test_k8s_endpoint_resource_delegate.py
For each endpoint, adds a pod disruption budget to make sure we at least have one available pod during disruption
tested by creating / deleting an endpoint locally
=> Add pod disruption budget to all endpoints

model-engine/model_engine_server/core/celery/app.py
The endpoint-builder and celery forwarder both use this celery app sessions instantiations. However, they expect different profiles to be used. Force the celery worker to use the dynamic value in `AWS_PROFILE` instead of the static `profile_ml_worker`.
Create a new deployment in our clusters and launched a batch job. The pods were built correctly and the job succeeded.
=> create celery worker with inference worker profile

charts/model-engine/templates/service_template_config_map.yaml
To guarantee QoS for http forwarder we should set higher CPU requests
=> Bump http forwarder request CPU

docs/guides/fine_tuning.md, docs/model_zoo.md
Also update docs to reflect that mistral-7b is available
=> [Docs] Clarify get-events API usage

charts/model-engine/templates/_helpers.tpl, model-engine/model_engine_server/common/env_vars.py, model-engine/model_engine_server/infra/gateways/live_batch_job_orchestration_gateway.py, model-engine/model_engine_server/infra/gateways/live_docker_image_batch_job_gateway.py, model-engine/model_engine_server/infra/gateways/resources/k8s_resource_types.py, model-engine/model_engine_server/infra/services/docker_image_batch_job_llm_fine_tuning_service.py
All jobs launched from llm-engine api will now have additional tags (e.g `request_id`). Should help us follow the life of a request a bit more. 
Used `just up` and confirmed that additional tags show in created `job` k8s resources.
=> Enable additional Datadog tagging for jobs

model-engine/model_engine_server/core/celery/app.py, model-engine/model_engine_server/inference/forwarding/celery_forwarder.py, model-engine/model_engine_server/infra/gateways/celery_task_queue_gateway.py
Follow-up to https://github.com/scaleapi/llm-engine/pull/327
The celery task queue is instantiated with `aws_profile` provided in this line. Tasks were completed but the final state was not written to s3 and silently failed since the profile used was not the one with s3 write permissions. The real issue is only with the Celery forwarder that is created with the wrong profile. Change only for its instantiation.
Create a new deployment in our clusters and launched a batch job. The pods were built correctly and the job successfully completed.
=> fix celery worker profile for s3 access

clients/python/llmengine/data_types.py, clients/python/llmengine/model.py, docs/api/python_client.md, model-engine/model_engine_server/core/celery/app.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/infra/gateways/k8s_resource_parser.py, model-engine/tests/unit/infra/gateways/test_k8s_resource_parser.py
=> Add docs for Model.create, update default values and fix per_worker concurrency

model-engine/model_engine_server/core/celery/app.py, model-engine/model_engine_server/inference/forwarding/celery_forwarder.py, model-engine/model_engine_server/infra/gateways/celery_task_queue_gateway.py
Reverts scaleapi/llm-engine#333
I think this caused an issue:
```
[2023-10-23 20:00:55,721: ERROR/MainProcess] Pool callback raised exception: ClientError('An error occurred (AccessDenied) when calling the PutObject operation: Access Denied')
```
=> Revert "fix celery worker profile for s3 access"

charts/model-engine/templates/_helpers.tpl, charts/model-engine/templates/service_config_map.yaml, charts/model-engine/values.yaml, charts/model-engine/values_circleci.yaml, charts/model-engine/values_sample.yaml, docs/guides/self_hosting.md, model-engine/model_engine_server/common/config.py, model-engine/model_engine_server/infra/gateways/resources/k8s_endpoint_resource_delegate.py, model-engine/model_engine_server/infra/gateways/resources/k8s_resource_types.py, model-engine/model_engine_server/infra/gateways/resources/templates/service_template_config_map_circleci.yaml, model-engine/model_engine_server/infra/services/live_endpoint_builder_service.py, model-engine/service_configs/service_config_circleci.yaml
confirmed that setting DATADOG_TRACE_ENABLED=false in a pod does nothing, but setting DD_TRACE_ENABLED=false in a pod successfully turns off datadog logging
=> Change DATADOG_TRACE_ENABLED to DD_TRACE_ENABLED

model-engine/model_engine_server/api/dependencies.py, model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/core/auth/authentication_repository.py, model-engine/model_engine_server/domain/gateways/monitoring_metrics_gateway.py, model-engine/model_engine_server/infra/gateways/fake_monitoring_metrics_gateway.py, model-engine/tests/unit/conftest.py
Emit metrics on each route calls for the LLM endpoints.
Tested locally with:
```bash
curl -H "Authorization: <AUTH>" http://localhost:5001/v1/llm/model-endpoints
```
```bash
curl -H "Content-Type: application/json" -H "Authorization: <AUTH>" -d '{ "prompt": "Hello!", "max_new_tokens": 10, "temperature": 0.1 }' http://localhost:5001/v1/llm/completions-sync?model_endpoint_name=llama-2-7b-test-vllm
```
=> Track LLM Metrics

model-engine/model_engine_server/api/batch_jobs_v1.py, model-engine/model_engine_server/api/docker_image_batch_job_bundles_v1.py, model-engine/model_engine_server/api/files_v1.py, model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/api/model_bundles_v1.py, model-engine/model_engine_server/api/model_bundles_v2.py, model-engine/model_engine_server/api/model_endpoints_v1.py, model-engine/model_engine_server/api/tasks_v1.py, model-engine/model_engine_server/api/triggers_v1.py, model-engine/model_engine_server/common/datadog_utils.py
https://docs.datadoghq.com/tracing/metrics/metrics_namespace/
> Trace metrics tags, possible tags are: env, service, version, resource, sublayer_type, sublayer_service, http.status_code, http.status_class, Datadog Agent tags (including the host and second primary tag). Note: Tags set on spans do not count and will not be available as tags for your traces metrics.
There already is a resource trace metric tag. `launch.resource_name` is also a facet that's unused, so it can be removed
=> Remove extra trace facet "launch.resource_name"

charts/model-engine/templates/service_template_config_map.yaml, model-engine/model_engine_server/infra/gateways/resources/k8s_resource_types.py
Mount aws configs to non-root directory. 
Tested by deploying runnable bundle (echo_server) and hitting with a sync task.
=> Unmount aws config from root

.circleci/config.yml, model-engine/model_engine_server/api/llms_v1.py, model-engine/requirements-test.txt
Used `diff-cover` for automated code coverage. In my `temp` commit, I wrote an endpoint that wasn't covered by unit tests and this is what I got: 
=> Implement automated code coverage for CI

charts/model-engine/templates/istio-metrics.yaml
Using variable name to remain consistent with other Helm resources.
Verified resource is valid and variables properly filled in.
```
helm template --debug model-engine model-engine -s templates/istio-metrics.yaml -f ../../model-engine-internal/model-engine-internal/resources/values/values_training.yaml 
```
=> Use Variable name for Telemetry Helm Resources

model-engine/model_engine_server/inference/configs/service--forwarder-runnable-img-converted-from-artifact.yaml, model-engine/model_engine_server/inference/configs/service--forwarder.yaml, model-engine/model_engine_server/inference/configs/service--http_forwarder.yaml, model-engine/model_engine_server/inference/forwarding/echo_server.py, model-engine/model_engine_server/inference/forwarding/forwarding.py, model-engine/tests/unit/inference/test_forwarding.py
We used to always forward with 200s ignoring downstream HTTP codes, now forwarding the code as well
unit tests and tested with echo server to make sure 500 status was forwarded
```
curl -X POST localhost:5000/predict -d '{"args":{}}' -H "content-type:application/json" -vv
Note: Unnecessary use of -X or --request, POST is already inferred.
* processing: localhost:5000/predict
*   Trying [::1]:5000...
* Connected to localhost (::1) port 5000
> POST /predict HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.68.0
> Accept: */*
> content-type:application/json
> Content-Length: 11
> 
< HTTP/1.1 500 Internal Server Error
< date: Tue, 14 Nov 2023 21:23:58 GMT
< server: uvicorn
< content-length: 15
< content-type: application/json
< 
* Connection #0 to host localhost left intact
{"result":"{}"} …
```
=> Forward HTTP status code for sync requests

.circleci/config.yml, charts/model-engine/values_circleci.yaml, integration_tests/test_fine_tunes.py, model-engine/model_engine_server/inference/pytorch_or_tf.base.Dockerfile
Add e2e integration test for fine-tuning. Also changed the base docker image for loading integration tests onto minikube to `python3.8:slim` instead since it originally took 10 minutes -- now it only takes 4 min! Let me know if this breaks anything else.
=> Fine-tuning e2e integration test

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
Also, let's just avoid the vLLM error by making sure max_num_batched_tokens >= max_model_len
=> Found a bug in the codellama vllm model_len logic.

charts/model-engine/templates/service_template_config_map.yaml, model-engine/model_engine_server/infra/gateways/resources/templates/service_template_config_map_circleci.yaml
Pull policy for these images should be IfNotPresent, otherwise minikube wouldn't be able to load them and fine tune jobs can't start. i'm not sure how finetune integration tests have been passing (maybe we actually pulled the image from minikube?)
=> Fix integration test

model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/gateways/monitoring_metrics_gateway.py, model-engine/model_engine_server/infra/gateways/fake_monitoring_metrics_gateway.py
add metrics on token counts for prompt, completion, and total
tested locally and on test deployment in training cluster
=> emit metrics on token counts

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
Increase max input tokens for llama-2
=> Increase llama-2 max_input_tokens

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
Reverts scaleapi/llm-engine#380
=> Revert "Found a bug in the codellama vllm model_len logic."

integration_tests/test_endpoints.py, integration_tests/test_fine_tunes.py
Some updates to integration tests
=> Some updates to integration tests

clients/python/llmengine/data_types.py
adds tensorrt-llm to enum for valid inference frameworks. currently `Model.list()` is broken due to the addition of endpoints that use tensorrt-llm as an inference framework when this framework isn't an option in the client. 
Ex: 
```
ValidationError: 1 validation error for ListLLMEndpointsResponse
model_endpoints -> 13 -> inference_framework
value is not a valid enumeration member; permitted: 'deepspeed', 'text_generation_inference', 'vllm', 'lightllm' (type=type_error.enum; enum_values=[<LLMInferenceFramework.DEEPSPEED: 'deepspeed'>, <LLMInferenceFramework.TEXT_GENERATION_INFERENCE: 'text_generation_inference'>, …
```
=> update tensor-rt llm in enum

clients/python/llmengine/__init__.py, clients/python/llmengine/data_types.py, clients/python/pyproject.toml, clients/python/setup.py
This pr fixes a mistake introduced in https://github.com/scaleapi/llm-engine/pull/390 where I mistakenly used a `-` instead of a `_` for the inference framework. merging the pr and bumping the pypi client will fix pydantic `Model.list()` issues.
Local deployment of the client installed with `pip install -e .` and then running `Model.list()` works without issue.
=> fixing tensorrt-llm enum value (fixes #390)

model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/infra/gateways/fake_monitoring_metrics_gateway.py
the use case for completions (sync and stream) includes preprocessing + forwarding request to the model + postprocessing. time the entire flow for total tokens per second
test deployment
=> time completions use case

model-engine/model_engine_server/common/datadog_utils.py, model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/domain/test_llm_use_cases.py
have completions use the same request id as that was generated by the middleware
local
=> fix completions request id

model-engine/model_engine_server/db/base.py
Getting errors like
```
File "/workspace/model-engine/model_engine_server/infra/repositories/db_model_endpoint_record_repository.py", line 236, in get_model_endpoint_record
model_endpoint_orm = await OrmModelEndpoint.select_by_id(
File "/workspace/model-engine/model_engine_server/db/models/hosted_model_inference.py", line 589, in select_by_id
endpoint = await session.execute(
.......
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 5 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
```
apparently there's some traffic spike(?) that caused too many connections to the postgres connection pool
_What is this PR changing? Why is this change being made? Any caveats you'd like to highlight? Link any relevant documents, links, …
=> 4x sqlalchemy pool size

charts/model-engine/Chart.yaml, charts/model-engine/templates/celery_autoscaler_stateful_set.yaml
Un-hardcode the autoscaler's nodeSelector
Dry-run helm applied with a sample yaml for fixed + not-fixed helm charts. Saw nodeSelector was changed accordingly using the branch's helm chart.
=> Fix autoscaler node selector

model-engine/model_engine_server/api/app.py, model-engine/model_engine_server/core/loggers.py
Log request sizes for debugging
tested locally
=> Log request sizes

model-engine/model_engine_server/api/model_endpoints_v1.py, model-engine/model_engine_server/domain/use_cases/model_endpoint_use_cases.py, model-engine/tests/unit/domain/test_model_endpoint_use_cases.py
- throw a 400 for `ObjectHasInvalidValueException` and `EndpointResourceInvalidRequestException` for update model endpoint route
- capture `EndpointInfraStateNotFound` as an explicit 500
update unit tests
=> handle update endpoint errors

model-engine/model_engine_server/core/utils/url.py, model-engine/model_engine_server/infra/gateways/s3_llm_artifact_gateway.py, model-engine/tests/unit/infra/gateways/test_s3_llm_artifact_gateway.py
with `s3_bucket.objects.filter(Prefix=key)`, an ending `/` has significance to how filtering works. create a new flag to turn off unexpected cleaning of keys.
update unit tests
=> [bug-fix] LLM Artifact Gateway .list_files()

charts/model-engine/values_circleci.yaml, charts/model-engine/values_sample.yaml, model-engine/model_engine_server/api/llms_v1.py, model-engine/model_engine_server/common/config.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/service_configs/service_config_circleci.yaml, model-engine/tests/unit/api/test_llms.py
Enable sensitive log mode for use cases that want avoid logging user-specific data (e.g prompts and responses)
Deploy in training and confirmed in datadog that logs no longer show up in vllm or logged by our gateway.
=> enable sensitive log mode

model-engine/model_engine_server/inference/batch_inference/requirements.txt, model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
1. use vllm 0.2.5 since 0.2.7 seems slower for the workload i tested 
2. add tqdm
=> Small update to vllm batch

clients/python/llmengine/__init__.py, clients/python/llmengine/data_types.py, clients/python/pyproject.toml, clients/python/setup.py
Fixes a bug where importing the python client with pydantic 2 installed raises an error. Will publish to pypi after merging the PR.
Imported client with pydantic 1.10 or pydantic 2 installed, imports succeed.
=> Allow using pydantic v2

clients/python/llmengine/__init__.py, clients/python/llmengine/data_types.py, clients/python/llmengine/model.py, clients/python/pyproject.toml, clients/python/setup.py
Previous pr allowed pydantic 2 to be compatible with the client, however we didn't update the requirements to note this.
Pip install -e and check which version of pydantic it asks for. It asks for `pydantic >= 1.10` which is correct.
=> Allow pydantic 2 in python client requested requirements

clients/python/llmengine/__init__.py, clients/python/llmengine/api_engine.py, clients/python/pyproject.toml, clients/python/setup.py
Add Basic Auth headers when people use the client's python async routes
Setting `LLM_ENGINE_BASE_PATH` to a self-hosted LLM Engine:
```
import asyncio
from llmengine import Completion
asyncio.run(Completion.acreate(model='llama-2-7b-chat', prompt='prompt'))
```
works. Without the change, we get 
```
<stack trace>
llmengine.errors.UnauthorizedError: No authentication was passed in
```
=> [Client] Add Auth headers to the python async routes

model-engine/model_engine_server/inference/requirements_base.txt
The model_engine_integration_tests are broken as is endpoint creation for endpoints where the user does not provide their own docker image. This is because our inference image does not pin some dependencies leading to this known issue with boto3 [here](https://github.com/boto/botocore/issues/3111). Thus we should pin to a safe version of urllib3 and boto3.
Notably, in the inference image generated right now, the following code crashes. We use the boto3 client when users request `return_picked=True`
```py
import boto3
s3_client = boto3.client("s3", region_name="us-west-2")
with open("/tmp/file.txt", 'rb') as f:
s3_client.upload_fileobj(f, "temp-edwardgan-test", "tmp/file")
```
I manually confirmed that these changes to the requirements.txt allow the above code to work in the docker image …
=> Pin boto3 and urllib3 versions to fix error in inference image

model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
Bring over flag added in https://github.com/vllm-project/vllm/pull/1976 to llm engine
test locally
without the flag:
```
> curl -H "Content-Type: application/json" -H "Authorization: Basic <AUTH>" -d '{ "prompt": "Whats 2+2? ", "stop_sequences": ["\n"], "max_new_tokens": 10, "temperature": 0.1 }' http://localhost:5000/v1/llm/completions-sync?model_endpoint_name=llama-7b-vllm-test-temp
{"request_id":"907c759f-e704-4d32-98a5-4dbe388ec04a","output":{"text":"4.","num_prompt_tokens":9,"num_completion_tokens":3,"tokens":null}}
```
note: `"4."` above
with the flag:
```
> curl -H "Content-Type: application/json" -H "Authorization: Basic <AUTH>" -d '{ "prompt": "Whats 2+2? ", "stop_sequences": ["\n"], "max_new_tokens": 10, "temperature": 0.1, "include_stop_str_in_output": true }' …
```
=> include stop string in completions output

model-engine/model_engine_server/api/dependencies.py, model-engine/model_engine_server/common/constants.py, model-engine/model_engine_server/core/config.py, model-engine/model_engine_server/domain/entities/model_endpoint_entity.py, model-engine/model_engine_server/domain/exceptions.py, model-engine/model_engine_server/inference/async_inference/tasks.py, model-engine/model_engine_server/inference/domain/gateways/streaming_storage_gateway.py, model-engine/model_engine_server/inference/forwarding/forwarding.py, model-engine/model_engine_server/inference/infra/gateways/firehose_streaming_storage_gateway.py, model-engine/model_engine_server/inference/post_inference_hooks.py, model-engine/model_engine_server/inference/sync_inference/fastapi_server.py, model-engine/model_engine_server/infra/gateways/resources/k8s_resource_types.py, model-engine/tests/integration/inference/conftest.py, model-engine/tests/unit/conftest.py, model-engine/tests/unit/inference/test_forwarding.py, model-engine/tests/unit/inference/test_http_forwarder.py, model-engine/tests/unit/infra/gateways/test_firehose_streaming_storage_gateway.py
Logging post inference hook to firehose stream. 
Runs successfully locally. Load test of 1000 requests success (finished in < 1min and all show up in table).
=> Logging post inference hook implementation

model-engine/model_engine_server/inference/async_inference/tasks.py, model-engine/model_engine_server/inference/sync_inference/fastapi_server.py
Post inference hooks handling should only occur in the forwarder container, not main container. Currently, the hooks are executed even in the main container, resulting in unnecessary and incorrect error logs in datadog.
=> Remove post inference hook handling in main container

model-engine/model_engine_server/inference/domain/gateways/streaming_storage_gateway.py, model-engine/model_engine_server/inference/infra/gateways/firehose_streaming_storage_gateway.py, model-engine/model_engine_server/inference/post_inference_hooks.py, model-engine/tests/unit/infra/gateways/test_firehose_streaming_storage_gateway.py
Clean up logs for logging hook and add better error info.
=> Clean up logs for logging hook

charts/model-engine/templates/endpoint_builder_deployment.yaml, model-engine/model_engine_server/api/dependencies.py, model-engine/model_engine_server/common/settings.py, model-engine/model_engine_server/entrypoints/start_batch_job_orchestration.py, model-engine/model_engine_server/service_builder/celery.py
https://github.com/scaleapi/llm-engine/pull/425/files moved the infra gateway from redis to sqs preemptively. 
move service builder (backbone for infra task gateway) to sqs
local deploy
=> Fix Infra Task Gateway

docs/model_zoo.md, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/inference/vllm/requirements.txt, model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py, model-engine/requirements.in, model-engine/requirements.txt
Add support for gemma models:
* gemma-2b
* gemma-2b-instruct
* gemma-7b
* gemma-7b-instruct
Update to `vllm==0.3.2`
* launched 2b models with 1 A10 GPU
* launched 7b models with 2 A10 GPUs
=> support gemma models

model-engine/model_engine_server/inference/post_inference_hooks.py
Logs emitted at timestamp for logging. 
=> Add emitted timestamp for logging

integration_tests/test_endpoints.py
I run into this almost every time I deploy to prod where the cache requires more time to update the resource state of the endpoint for the `test_async_model_endpoint` integration test.
=> Change cache update time for async endpoint integration test

scripts/throughput_benchmarks.py
Allow passing in a json-formatted list of output token counts
Ran the script
=> Allow the load test script to use a csv of inputs

model-engine/model_engine_server/domain/use_cases/model_endpoint_use_cases.py, model-engine/tests/unit/api/test_model_endpoints.py
This generalizes the logic in llm engine to look for a plugin that can validate both team and product. The goal is to be able to support conventions where the set of products allowed depends on the team label, like the one here [doc](https://docs.google.com/document/d/1CXDMeEWkdSvK32HuUn1-rdm_jnNFuvCpeRCEzKVCvbQ/edit) using a shared plugin between launch and train. 
We keep the old code for just checking the team using a plugin around even though it will no longer be necessary so that llm-engine code is backwards compatible with deployments that are not yet using the new extended plugin.
CI. Manual testing with internal code in https://github.com/scaleapi/models/pull/8924 .
Also note that this PR re-enables some API tests that attempt to create endpoints with invalid team labels. …
=> Add product label validation

docs/guides/completions.md, model-engine/model_engine_server/inference/batch_inference/Dockerfile_vllm, model-engine/model_engine_server/inference/batch_inference/vllm_batch.py, model-engine/model_engine_server/inference/vllm/vllm_server.py, model-engine/model_engine_server/infra/services/image_cache_service.py, model-engine/tests/unit/infra/services/test_image_cache_service.py
1. Add batch inference to llm engine guides
2. Cache vllm batch inference docker image
3. Use lower GPU mem utilization to avoid random OOM, also some logging if there's abnormal GPU mem usage at start
=> Some batch inference improvements

clients/python/llmengine/__init__.py, clients/python/llmengine/data_types.py, clients/python/pyproject.toml, clients/python/setup.py
Add a quick `num_prompt_tokens` field to the client's CompletionOutput/CompletionStreamOutput.
Originally wanted to add `include_stop_str_in_output`, but that requires various server changes to get functional, so I didn't include it here.
Ran against Scale public APIs plus a hosted version. `num_prompt_tokens` exists if it's in the http response.
=> [Client] Add num_prompt_tokens to the client's CompletionOutputs

integration_tests/test_docs.py
`integration_tests/test_docs` pointed to default gateway instead of integration test gateway. fix this
`just _integration_test training test_docs`
=> fix docs tests gateway endpoint

clients/python/llmengine/__init__.py, clients/python/llmengine/completion.py, clients/python/llmengine/data_types.py, clients/python/pyproject.toml, clients/python/setup.py, docs/guides/completions.md, model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/inference/vllm/requirements.txt, model-engine/model_engine_server/inference/vllm/vllm_server.py, model-engine/tests/unit/conftest.py, model-engine/tests/unit/domain/conftest.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Support guided_json, guided_regex, guided_choice from vLLM
tested within vllm entrypoint and from model engine
```
curl localhost:5005/predict -d '{"prompt":"hello", "guided_regex":"a beautiful world .*"}'
{"text": "a beautiful world is fuxix", "count_prompt_tokens": 2, "count_output_tokens": 16, "log_probs": null, "tokens": ["a", " ", "b", "ea", "u", "t", "iful", " ", "wo", "r", "l", "d", " is", " f", "ux", "ix"]}
```
=> Guided decoding

model-engine/model_engine_server/api/tasks_v1.py, model-engine/model_engine_server/infra/gateways/celery_task_queue_gateway.py, model-engine/tests/integration/inference/test_async_inference.py, model-engine/tests/unit/api/test_tasks.py
Return 400 for some client errors
tested calling an endpoint with long message and received:
`<Response [400]>`
```
{"detail":"Invalid request: Error sending celery task: An error occurred (InvalidParameterValue) when calling the SendMessage operation: One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes."}
```
=> Return 400 for botocore client errors

model-engine/model_engine_server/core/docker/kaniko_template.yaml
- increase kaniko job memory to 90Gi
- also add push retries in case that step fails
tested on job
=> Increase Kaniko Memory

model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
we shouldn't be using `model` from vLLM, which is always the folder `MODEL_WEIGHTS`, instead use the base model name from the request.
tested local run w and w/o tool use
=> Use base model name as metric tag

model-engine/model_engine_server/inference/batch_inference/vllm_batch.py, model-engine/model_engine_server/inference/vllm/requirements.txt, model-engine/model_engine_server/inference/vllm/vllm_server.py, model-engine/tests/unit/inference/conftest.py
since vLLM > 0.3.3, `logprobs` are returned as as type `Logprob` instead as direct float's. it's an API-breaking change (see https://github.com/vllm-project/vllm/pull/3065#issuecomment-1984761326)
change `vllm_server` to return output in the same previous format
create new `llama-2-7b` with vLLM==0.4.0.post1
```python
Completion.create(
model="llama-2-7b",
prompt="Hello ",
max_new_tokens=10,
temperature=0.0,
return_token_log_probs=True,
)
```
=> fix return_token_log_probs on vLLM > 0.3.3 endpoints

model-engine/README.md, model-engine/model_engine_server/infra/services/live_endpoint_builder_service.py, model-engine/requirements.in, model-engine/requirements.txt, model-engine/tests/unit/conftest.py, model-engine/tests/unit/infra/services/test_live_endpoint_builder_service.py, requirements-dev.txt
* Upgrade poetry to 1.8.2 to fix package version conflicts with pip-tools in requirements-dev.txt
* Add docs on setting to `WORKSPACE` env var to be able to run tests locally
* Fix faulty `type: ignore` and handle type narrowing explicitly
* Add test case for high priority + zipartifact codepath for test coverage
Tested pip install + mypy + pytest on a fresh venv using python 3.8.10
```
python -m venv …
```
=> Package update + more docs on dev setup

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/infra/repositories/live_tokenizer_repository.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Enforce that model checkpoints are used when creating bundles to prevent outages/issues in prod where a hf repo becomes unavailable
=> Enforce model checkpoints existing for endpoint/bundle creation

charts/model-engine/templates/inference_framework_config.yaml, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
=> patch service config identifier

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/conftest.py, model-engine/tests/unit/domain/conftest.py, model-engine/tests/unit/domain/test_llm_use_cases.py
We now require safetensors for LLM endpoint creation. This helps to mitigate a potential security risk and optimizes performance for loading .safetensors vs .bin files.
create endpoint with and without safetensors
=> require safetensors for LLM endpoint creation

clients/python/llmengine/__init__.py, clients/python/pyproject.toml, clients/python/setup.py
Make the published client [PEP 561](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages) compatible so that downstream users can get type hinting
=> Add py.typed for proper typechecking support on clients

model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/inference/batch_inference/vllm_batch.py, model-engine/tests/unit/inference/conftest.py, model-engine/tests/unit/inference/test_vllm_batch.py
Up max gpu memory utilization to 0.95 for 70b models in attempt to address OOM issues
https://linear.app/scale-epd/issue/MLI-2309/use-095-gpu-memory-utilization-for-70b-models
Published test docker image for batch_inference. Tested with API request using local gateway: job `ft-cp21h54gfe6g02mlqikg`
=> Increase max gpu utilization for 70b models

model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/inference/batch_inference/Dockerfile_vllm, model-engine/model_engine_server/inference/batch_inference/requirements-build.txt, model-engine/model_engine_server/inference/batch_inference/requirements-dev.txt, model-engine/model_engine_server/inference/batch_inference/requirements.txt
Upgrade vLLM from 0.2.5 to 0.4.2 for batch completion job to support AWQ quantization with mixtral 8x7b. 
Caveats about upgrading:
* vLLM 0.4.2 uses pydantic 2, so will need to make the approach changes to the relevant dtos to support this upgrade
* vLLM 0.4.2 requires us to install flash attention 2 manually (e.g. https://github.com/vllm-project/vllm/pull/3396/files)
Tested batch job: …
=> Upgrade vLLM version for batch completion

model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/inference/batch_inference/Dockerfile_vllm, model-engine/model_engine_server/inference/batch_inference/requirements-build.txt, model-engine/model_engine_server/inference/batch_inference/requirements-dev.txt, model-engine/model_engine_server/inference/batch_inference/requirements.txt
Reverts scaleapi/llm-engine#518
This was not correctly done. Misses various other recursive imports and worst of all, [the import of openai's model](https://github.com/scaleapi/llm-engine/blob/4d0cd26087c3436b6bde2c722018d5b486e78fa9/model-engine/model_engine_server/common/dtos/model_endpoints.py#L146) makes this approach not feasible.
```
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:                                                          │
* 'orm_mode' has been renamed to 'from_attributes'                                                                                                                                     │
warnings.warn(message, UserWarning) …
```
=> Revert "Upgrade vLLM version for batch completion"

charts/model-engine/templates/balloon_h100_deployment.yaml, charts/model-engine/values_circleci.yaml, charts/model-engine/values_sample.yaml, clients/python/llmengine/__init__.py, clients/python/llmengine/model.py, clients/python/pyproject.toml, clients/python/setup.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
- image cache for h100 + MIG
- balloon for H100, decided to not add for MIG for simplicity. can add later if needed
- temporarily stop people from using A100. will revert shortly
=> Image cache and balloon on H100s, also temporarily stop people from using A100

charts/model-engine/values_sample.yaml, model-engine/model_engine_server/common/config.py, model-engine/model_engine_server/core/celery/app.py, model-engine/model_engine_server/core/config.py
Add an option to have the pods read Redis auth info from an AWS secret.
Note: there are two places the redis auth info needs to be added, since Redis is used for both the model endpoint creation request message queue and a cache for endpoint info
The secret is formatted as follows:
It must contain a few keys, namely `host`, `port`, `scheme` (optional, defaults to `redis://`), `auth_token` (optional), `query_params` (optional). These control which Redis gets used as the message queue for the endpoint builder. Also must contain a key `cache-url`, the full Redis url of the redis to be used as a cache.
Deployed helm chart with a values.yaml that asks to get the redis url from the secret. The pods start up fine.
=> Option to read Redis URL from AWS Secret

model-engine/model_engine_server/inference/pytorch_or_tf.base.Dockerfile
seeing tzdata installation hanging due to region selection: https://app.datadoghq.com/logs?query=kube_job%3Akaniko-4079a805%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1717453458877&to_ts=1717457058877&live=true
add non-interactive installation as referred in https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai
this appears to happen building images using newer pytorch base images like `2.1.0-cuda12.1-cudnn8-runtime`
_How did you validate that your PR works correctly? How do you run or demo the code? Provide enough detail so a reviewer can reasonably reproduce the testing procedure. Paste …
=> Non-interactive installation during docker build

clients/python/llmengine/__init__.py, clients/python/llmengine/completion.py, clients/python/llmengine/data_types.py, clients/python/pyproject.toml, clients/python/setup.py
Add `guided_grammar` to the client, + add some missing fields to some codepaths
Tried running `Completions.create()` with the new `guided_grammar` arg (and the rest of the `guided*` args) (both async create and sync create, both stream and non-stream) and they work.
=> [Client] Add guided_grammar and other missing fields

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Update hardware inference logic to increase min kv cache allocated for batch jobs. This will improve batch completion throughput for larger models (e.g. llama-3-70b)
=> Bump kv cache min memory for batch jobs

model-engine/model_engine_server/api/llms_v1.py
Debugging some issues where user gets sporadic errors when getting a model endpoint
=> DEBUG: Add additional logging for authz errors

model-engine/model_engine_server/inference/vllm/vllm_server.py
There is a known error where vLLM's AsyncEngine will fail silently on OOM, but the webserver will continue running. There was a previous attempt at fixing this, but it didn't fully capture the line the error was happening. 
Stack trace:
```
File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
return await dependant.call(**values)
File "/workspace/vllm_server.py", line 112, in generate
async for request_output in results_generator:
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 666, in generate
raise e
File …
```
=> Mitigation for AsyncEngineDeadError

clients/python/llmengine/data_types.py, model-engine/model_engine_server/common/dtos/llms.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/inference/batch_inference/build_and_upload_image.sh, model-engine/model_engine_server/inference/batch_inference/vllm_batch.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Adds an option to show the special tokens in completions/stream completions/batch completions output
Completions/Stream completions
- Deploy a model (or grab one from somewhere) that has the special tokens
- Make request to model to see if special tokens are respected (with skip = False). Also try skip = True to sanity check
Made request with body ```{
"prompt": "Give me a list of all numbers. Sure! 1, 2",
"max_new_tokens": 10,
"temperature": 0.0,
"skip_special_tokens": false,
"guided_regex": "4"
}```, this gives output "4</s>", making same request with skip=true, output is just "4". Works for sync and stream.
Batch completions
- Make batch completions call using model with special tokens
- See whether output has the special tokens
Made batch completions calls with both skip special …
=> Add special token param to completions + batch completions apis

integration_tests/rest_api_utils.py, integration_tests/test_completions.py
vLLM integration tests for the stream case has a few bugs that this addresses
=> Fix integration tests for streaming case

model-engine/model_engine_server/inference/forwarding/http_forwarder.py, model-engine/tests/unit/inference/test_http_forwarder.py
Quick change to increase the allowed concurrency to http endpoints
todo integration tests
=> Increase default concurrency to 100 for http forwarder

clients/python/llmengine/data_types.py, clients/python/llmengine/model.py
infer hardware when users don't specify cpu/gpu/memory/storage/gpu_type, also some docs
tested with
```
from llmengine import Model, api_engine
api_engine.set_api_key(<key>)
api_engine.set_base_path(<base_path>)
response = Model.create(
name="llama-2-70b-test",
model="llama-2-70b",
inference_framework_image_tag="0.5.0",
inference_framework="vllm",
num_shards=4,
min_workers=0,
max_workers=1,
per_worker=10,
endpoint_type="streaming",
public_inference=False,
labels={"team": "infra", "product": "test"},
)
```
=> Allow hardware infer from client

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/domain/conftest.py, model-engine/tests/unit/domain/test_llm_use_cases.py
request.metadata is only set when certain fields are updated. This causes issues where endpoint metadata is reset when other fields are updates (e.g. min_workers).
This change updates the behavior to retain existing endpoint metadata if they exist
=> More rigorous endpoint update handling

model-engine/model_engine_server/core/celery/celery_autoscaler.py
Some customers deploy in different AWS regions
Pod has AWS_REGION so it should work or default to previous behaviour
=> fix: Use env AWS_REGION in sqs_client or default to us-west-2

model-engine/model_engine_server/infra/gateways/live_streaming_model_endpoint_inference_gateway.py, model-engine/model_engine_server/infra/gateways/live_sync_model_endpoint_inference_gateway.py, model-engine/tests/unit/infra/gateways/test_live_sync_model_endpoint_inference_gateway.py
sometimes requests are wrapped and so are error details. do one extra step to get the data out
with the help of @Tma2333-Scale, tested for exception within the API (verified that we can get traceback),
and for exception from Pydantic before reaching to the API:
=> Parse wrapped sync endpoint error

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/domain/conftest.py
The current implementation for data parallelism has a race condition where gpus can be fully utilized by 1 worker across many jobs and cause a deadlock while they wait for the other workers to spin up. Disabling this feature until we fix this bug
=> Disable data parallelism for batch completions

model-engine/model_engine_server/inference/batch_inference/vllm_batch.py
Allow skipping setting AWS_PROFILE, if we're in environments that handle setting AWS_PROFILE for us
will run a job on such an environment, if it works then I will be happy and merge this.
=> Option to skip AWS profile set

model-engine/model_engine_server/db/migrations/alembic/versions/2024_09_24_1456-f55525c81eb5_multinode_bundle.py, model-engine/model_engine_server/db/models/hosted_model_inference.py, model-engine/model_engine_server/domain/entities/model_bundle_entity.py, model-engine/model_engine_server/infra/repositories/db_model_bundle_repository.py
Add two columns for worker command + worker env to the bundle table + orm class + entity class
the integration tests do seem to exercise the db migration which is pretty cool, and it caught a typo where I named the column in the migration script wrong
will run db migration after merge
=> Multinode bundle db migration + orm class + entity

clients/python/llmengine/__init__.py, clients/python/llmengine/completion.py, clients/python/llmengine/data_types/batch_completion.py, clients/python/pyproject.toml, clients/python/setup.py
=> Add hardware spec to client

model-engine/model_engine_server/common/dtos/llms/__init__.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/inference/vllm/vllm_batch.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Deepseek loads model configs + tokenizers through python files defined in checkpoint.
=> Add *.py files to model weights if trust_remote_code is provided

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
This reverts commit 7cb43cd026a36c15dc036c6b8bd41e6c4c5593ad.
It's a bit too soon to apply this change
=> Revert "Remove model name override (#641)"

clients/python/llmengine/data_types/completion.py, clients/python/llmengine/data_types/vllm.py, model-engine/model_engine_server/api/v2/batch_completion.py, model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
* Fix client usage of 'Annotated' type
* Add request id to batch completions API failures
=> Miscellaneous improvments

model-engine/model_engine_server/api/dependencies.py, model-engine/tests/unit/api/conftest.py
Support bearer token auth. This allows openai client to be used against llmengine with no additional headers
=> Bearer auth for oai compatibility

model-engine/model_engine_server/db/migrations/alembic/env.py
This requirement is too strict. ENV is not a guaranteed environemntal variable
=> Remove ENV requirement for db migration

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/model_engine_server/inference/vllm/build_and_upload_image.sh, model-engine/tests/unit/domain/test_llm_use_cases.py
Remove hardcoded check on model name
=> Remove restrictive model name check

clients/python/llmengine/__init__.py, clients/python/llmengine/model.py, clients/python/pyproject.toml, clients/python/setup.py
Pass said parameter to vLLM engine if requested by user
=> Add max_model_len as Optional Argument for Model.create API

charts/model-engine/Chart.yaml, charts/model-engine/templates/service_template_config_map.yaml, charts/model-engine/values.yaml
Allow the `cooldownPeriod` used in keda for autoscaling to be set as a helm value.
Ran `helm template model-engine model-engine/ -f model-engine/values_circleci.yaml` to validate it gets populated as intended
=> Make cooldown period configurable

.circleci/config.yml, model-engine/.coveragerc, model-engine/model_engine_server/inference/forwarding/celery_forwarder.py, model-engine/model_engine_server/inference/forwarding/forwarding.py, model-engine/model_engine_server/infra/gateways/celery_task_queue_gateway.py
Kick requests back to the queue if an async worker is shutting down, by seeing if we hit a ConnectionError.
Note: If a request gets kicked back to the queue, the status goes from STARTED to PENDING. This masks a "RETRY" status from Celery. I didn't want to break backwards compatibility.
Put a test deployment on the cluster and made requests to it while scaling down the workers. The tasks eventually all succeed. Before, some tasks would fail.
=> Don't fail async task on pod termination

charts/model-engine/Chart.yaml, model-engine/model_engine_server/core/celery/celery_autoscaler.py
Use the `celery.scaleml.autoscaler/cooldownPeriodSeconds` annotation to customize the cooldown period (how long the deployment stays up for after it has been autoscaled up).
For the initial version, will just rely on editing the deployment to add this annotation.
=> [SGP] Add cooldown period customizability for celery through annotations

model-engine/model_engine_server/infra/gateways/resources/k8s_endpoint_resource_delegate.py, model-engine/model_engine_server/infra/services/live_endpoint_builder_service.py, model-engine/model_engine_server/infra/services/live_model_endpoint_service.py, model-engine/tests/unit/infra/gateways/resources/test_k8s_endpoint_resource_delegate.py
Found a silly mistake in the code that runs in the cacher, which led to cacher errors on some old deployments
Also bump ttl
Will deploy to cluster and see if the error messages are still there, which they aren't
=> fix dumb mistake in cacher, also bump the ttl

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py, model-engine/tests/unit/domain/test_llm_use_cases.py
Default nodes_per_worker to 1 if not provided, still infer hardware if not all of cpus/gpus/gpu type/storage/mem provided. Bug was that we'd pass nodes_per_worker as None to the gateway, which arguably can be considered not according to spec
Unit tests
=> Fix small nodes_per_worker bug in batch completions v2

charts/model-engine/Chart.yaml, charts/model-engine/templates/cacher_vpa.yaml, charts/model-engine/templates/endpoint_builder_vpa.yaml
Change the vpa recommender settings to have gateway, cacher, and endpoint builder share the same updateMode; currently it's set so the cacher and endpoint builder are more aggressive in getting scaled in recommendations. Also I noticed a boot loop with the cacher, this should fix things
=> switch cacher and endpoint builder to the same updateMode as the gateway

charts/model-engine/Chart.yaml, charts/model-engine/templates/gateway_deployment.yaml, model-engine/model_engine_server/entrypoints/start_fastapi_server.py
So it matches with --timeout 60 in start_fastapi_server.py
=> fix: Sets terminationGracePeriodSeconds: 60 and adds --graceful-timeout 60 to entrypoint

model-engine/model_engine_server/inference/vllm/vllm_batch.py
This PR adds `AWS_EC2_METADATA_DISABLED=true` to the environment when launching s5cmd in the batch inference script. This prevents the AWS SDK from attempting to access the EC2 metadata service, which is not available in GKE.
=> MLI-3695 Add disable EC2 metadata for batch completions

charts/model-engine/Chart.yaml, charts/model-engine/templates/_helpers.tpl, charts/model-engine/templates/endpoint_builder_deployment.yaml, charts/model-engine/values_sample.yaml, model-engine/model_engine_server/common/settings.py, model-engine/model_engine_server/infra/gateways/live_model_endpoint_infra_gateway.py, model-engine/tests/unit/common/test_settings.py
Allows to set model engine service builder queue name
Required to run multiple instances of Model Engine in same AWS account
=> fix: Adds serviceBuilderQueue

model-engine/model_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py
The new changes to vllm server image default to using ipv4 unless --host is provided. This is reasonable design, which means we should update our code to pass in --host :: explicitly. 
TODO: parameterize ipv6 vs ipv4 cluster for endpoints
=> Default ipv6 for vllm

federal/Dockerfile.chainguard, model-engine/model_engine_server/db/migrations/alembic/versions/2025_09_16_1741-e580182d6bfd_add_passthrough_forwarder.py, model-engine/model_engine_server/db/models/hosted_model_inference.py, model-engine/model_engine_server/domain/entities/model_bundle_entity.py, model-engine/model_engine_server/infra/repositories/db_model_bundle_repository.py
Adding a column to persist the forwarder type
=> Persist Forwarder Type
